# Generated by Django 3.0.7 on 2020-06-12 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expiration_list', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='expirationlist',
            new_name='expiration_list',
        ),
        migrations.RemoveField(
            model_name='expirationlist',
            name='user',
        ),
    ]
