# Generated by Django 3.0.7 on 2020-06-12 19:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('expiration_list', '0003_auto_20200612_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='date_bought',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
