# Generated by Django 3.0.7 on 2020-06-13 02:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('expiration_list', '0004_item_date_bought'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='date_expired',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
