# Generated by Django 3.0.7 on 2020-06-13 21:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('expiration_list', '0005_item_date_expired'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='days_left',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
